### ISSUE TITLE
Replicate examples from the examples repo

### ISSUE THREAD

**Issue by jayvdb** [shuttle-hq/shuttle-docs#108]
This task is to extract the examples from https://github.com/shuttle-hq/shuttle-examples , and use them to populate the  examples section here in the docs, e.g. https://docs.shuttle.rs/examples/axum . 

As the examples for each framework are currently on a single page, it is likely easier to place the examples on separate pages, as they are separate in the shuttle-examples repo.  This is what https://github.com/shuttle-hq/shuttle-docs/issues/86 suggests.

**Comment by ivancernja** [comment]
Thanks for reporting this @jayvdb -- we've merged that fix not too long ago!
