### ISSUE TITLE
Fix the deployment AWS region

### ISSUE THREAD

**Issue by peter-kehl** [shuttle-hq/shuttle-docs#162]
Thank you for Shuttle.rs. You rule!

- https://docs.shuttle.rs/introduction/how-shuttle-works > says "eu-west2", but
- https://docs.shuttle.rs/support/faq > "Where geographically are deployments hosted?" says "eu-west1".

Please check the reality and fix.

If you confirm which one is correct, I'm willing to provide a pull request.

**Comment by peter-kehl** [comment]
According to https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html eu-west-1 is in Ireland. eu-west-2 is in London.

**Comment by oddgrd** [comment]
Hey Peter, thanks! You are correct, the FAQ is wrong, a pull request would be great!

**Comment by sentinel1909** [comment]
I can take care of this one too, if @peter-kehl doesn't have time.
