### ISSUE TITLE
Add shuttle-metadata docs

### ISSUE THREAD

**Issue by oddgrd** [shuttle-hq/shuttle-docs#168]
We should add docs for ~~shuttle-service-info~~ shuttle-metadata, we can probably mostly reuse the crate docs, see: https://github.com/shuttle-hq/shuttle/pull/1129

Renaming PR: https://github.com/shuttle-hq/shuttle/pull/1165

**Comment by sentinel1909** [comment]
I can take care of this one.  Going to work on the persist update next, then can move on to this.

**Comment by sentinel1909** [comment]
I think this one can be closed, as the related PR with changes has been accepted and merged.
