### ISSUE TITLE
[shuttle-static-folder] placement of the folder seems wrong

### ISSUE THREAD

**Issue by auipga** [shuttle-hq/shuttle-docs#174]
> Note: if you use shuttle-static-folder in your project and your project is a workspace, the static assets folder needs to be in the root of the workspace.

https://github.com/shuttle-hq/shuttle-docs/blob/main/resources/shuttle-static-folder.mdx#L22

When I place the folder in the root of the workspace, it fails.
When I move it into my backend folder, it works.

**Comment by jonaro00** [comment]
You are right, and I'm close to having the solution merged in the next release (next week)! See https://github.com/shuttle-hq/shuttle/pull/1050
Docs will be updated accordingly.

The workaround right now is to use it in backend locally, but place it in root before deploying.
