### ISSUE TITLE
Secret for `local_uri` needs to be added to prod Secrets.toml for a successful deployment

### ISSUE THREAD

**Issue by auipga** [shuttle-hq/shuttle-docs#183]
When I use `shuttle_shared_db` I can make use of the `local_uri` parameter.
In conjunction with `shuttle-secrets` I can set this to `local_uri = "{secrets.DATABASE_URL}"`.

Even though the **local** uri is **only** used for local development, I need to set DATABASE_URL not only in `Secrets.dev.toml` but also in `Secrets.toml` 🤨

If the parameter is missing (at least defined with an empty string) it results in an error during the loading state:
> error="Failed to interpolate string. Is your Secrets.toml correct?"

Please add some clarification to the docs.

**Comment by jonaro00** [comment]
Closed in #187
