### ISSUE TITLE
How can i uninstall cargo-shuttle?

### ISSUE THREAD

**Issue by ayratmsk** [shuttle-hq/shuttle-docs#268]
How can i uninstall cargo-shuttle?

Despite the presence of .cargo/cargo-shuttle
terminal command $ cargo uninstall cargo-shuttle  doesn't succeed:
error: package ID specification `cargo-shuttle` did not match any packages

**Comment by jonaro00** [comment]
You can simply delete the cargo-shuttle (binary) file. You can find where it is (if it's on PATH) with `which cargo-shuttle`.

**Comment by joshua-mo-143** [comment]
Should we add something to the docs about this so the issue can be closed?
