### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by wiktorkujawa** [shuttle-hq/shuttle-docs#272]
Path: /examples/Axum-websockets

This example doesn't work:
It returns: `Connection header did not include 'upgrade'`
Also websocketUpgrade is updated and now it's inside extract::ws

**Comment by joshua-mo-143** [comment]
Hey Wiktor!

Are you still having this issue? It looks like the aforementioned issues have been fixed.

I used cURL and it seems to work using this command below:

```bash
curl --include \
     --no-buffer \
     --header "Connection: Upgrade" \
     --header "Upgrade: websocket" \
     --header "Host: localhost:8000" \
     --header "Origin: http://localhost:8000" \
     --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
     --header "Sec-WebSocket-Version: 13" \
     http://localhost:8000/websocket
     ```

**Comment by wiktorkujawa** [comment]
Hey Joshua,

Actually, after this update, shuttle CLI finally started working, so I was able to remove all previous failed substitute projects and restart the original one.

**Comment by joshua-mo-143** [comment]
No worries! Great to hear. I will close this issue for now then, since it seems everything is resolved.
