### ISSUE TITLE
Issue on docs migrating-to-shuttle

### ISSUE THREAD

**Issue by matzesoft** [shuttle-hq/shuttle-docs#277]
Path: /migration/migrating-to-shuttle

At the end of the file there is stated the command: `cargo shuttle project deploy`

This gives me the output:
```
error: unrecognized subcommand 'deploy'

Usage: cargo-shuttle project [OPTIONS] <COMMAND>

For more information, try '--help'.
```

If think this should be: `cargo shuttle deploy`

**Comment by joshua-mo-143** [comment]
You're right! This should have been amended a while ago. Will make a PR shortly to amend this.
