### ISSUE TITLE
Docs for contributing don't tell you to install docker buildx

### ISSUE THREAD

**Issue by GorgWorgington** [shuttle-hq/shuttle-docs#29]
While following the guide on [this page](https://docs.shuttle.rs/community/contribute#running-locally) I got stuck when running `make images` because gives weird `unknown flag: --build-arg` error, but installing the `docker-buildx` package on arch fixed it.

**Comment by oddgrd** [comment]
Oh, thanks! I think it's included with docker by default on a lot of systems, but maybe not arch. It's a good idea to add a note about this to the contributing docs. And I know it is a bit confusing, but it should be updated in the [main repo](https://github.com/shuttle-hq/shuttle/blob/main/CONTRIBUTING.md), a github workflow will automatically update it here after.

**Comment by sentinel1909** [comment]
I will take care of this update. I'm trying to practice and get comfortable contributing.

**Comment by sentinel1909** [comment]
Should this issue be closed out now that I've worked on it and the changes accepted?

**Comment by oddgrd** [comment]
Yes, I just need to figure out why the workflow bot didn't replicate the changes. 🤔

**Comment by oddgrd** [comment]
We fixed it, we had forgotten to enable actions for this repo :sweat_smile:
